apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: testrest-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: "localhost"
      http:
        paths:
          - path: /testrest(/|$)(.*)
            backend:
              serviceName: testrest-serv
              servicePort: 80
    - http:
        paths:
          - path: /testrest(/|$)(.*)
            backend:
              serviceName: testrest-serv
              servicePort: 80
    - host: "arch.homework"
      http:
          paths:
            - path: /otusapp(/|$)(.*)
              backend:
                serviceName: testrest-serv
                servicePort: 80

